# Generated by Django 6.0.7 on 2026-07-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='known_for',
            new_name='agriculture',
        ),
        migrations.AddField(
            model_name='village',
            name='culture',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='famous_places',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='festivals',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
